[package]
name = "evalessence-core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = {workspace = true}
serde_json = {workspace = true}
futures = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true